// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainLeft_1 = NULL;
SpeedController* RobotMap::driveTrainLeft_2 = NULL;
SpeedController* RobotMap::driveTrainLeft_3 = NULL;
SpeedController* RobotMap::driveTrainRight_1 = NULL;
SpeedController* RobotMap::driveTrainRight_2 = NULL;
SpeedController* RobotMap::driveTrainRight_3 = NULL;
Solenoid* RobotMap::driveTrainShifty = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveTrainLeft_1 = new Victor(1, 4);
	lw->AddActuator("DriveTrain", "Left_1", (Victor*) driveTrainLeft_1);
	
	driveTrainLeft_2 = new Victor(1, 5);
	lw->AddActuator("DriveTrain", "Left_2", (Victor*) driveTrainLeft_2);
	
	driveTrainLeft_3 = new Victor(1, 6);
	lw->AddActuator("DriveTrain", "Left_3", (Victor*) driveTrainLeft_3);
	
	driveTrainRight_1 = new Victor(1, 1);
	lw->AddActuator("DriveTrain", "Right_1", (Victor*) driveTrainRight_1);
	
	driveTrainRight_2 = new Victor(1, 2);
	lw->AddActuator("DriveTrain", "Right_2", (Victor*) driveTrainRight_2);
	
	driveTrainRight_3 = new Victor(1, 3);
	lw->AddActuator("DriveTrain", "Right_3", (Victor*) driveTrainRight_3);
	
	driveTrainShifty = new Solenoid(3, 1);
	lw->AddActuator("DriveTrain", "Shifty", driveTrainShifty);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
