// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/Drive.h"
DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	left_1 = RobotMap::driveTrainLeft_1;
	left_2 = RobotMap::driveTrainLeft_2;
	left_3 = RobotMap::driveTrainLeft_3;
	right_1 = RobotMap::driveTrainRight_1;
	right_2 = RobotMap::driveTrainRight_2;
	right_3 = RobotMap::driveTrainRight_3;
	shifty = RobotMap::driveTrainShifty;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void DriveTrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new Drive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void DriveTrain::Move(float left, float right)
{
	if (left < 0.05 && left > -0.05)
		left = 0;
	if (right < 0.05 && right > -0.05)
		right = 0;
	printf("MOVE! l:%f\tr:%f\n", left, right);
	
	left_1->Set(left);
	left_2->Set(left);
	left_3->Set(left);
	
	right_1->Set(right);
	right_2->Set(right);
	right_3->Set(right);
}

void DriveTrain::Shifting()
{
	if (shifty->Get())
		shifty->Set(false);
	else
		shifty->Set(true);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
